build dependency image:
  tags:
    - 1c-server
  rules:
    - changes:
      - dependency-image/Dockerfile
      - dependency-image/docker-compose.yml
  script:
    - cd dependency-image && docker-compose up --build --remove-orphans
build conveyor image:
  tags:
    - 1c-server
  rules:
    - changes:
      - conveyor-image/*
  script:
    - cd conveyor-image && docker-compose up --env-file config.env --build --remove-orphans